#!/usr/bin/env python3

# count and report occurances of consecutively repeated lines from stdin

import sys

if __name__=='__main__':
    lastCount=0
    lastItem=None
    for line in sys.stdin.readlines():
        line = line.rstrip() # remove trailing whitespace & newlines
        if (line == lastItem):
            lastCount += 1
        else:
            if (lastCount > 0):
                print("%d:%s" % (lastCount, lastItem))
            lastCount = 1
            lastItem = line
    if (lastCount > 0):
        print("%d:%s" % (lastCount, lastItem))
