#!/usr/bin/python

import sys
from subprocess import check_output

def getScreenDimensions():
  return (int(check_output(['tput','lines'])), int(check_output(['tput','cols'])))



if __name__=='__main__':


    # load data
    data = {}
    for line in sys.stdin.readlines()
        i = int(line)
        if i in data:
            data[i]+=1
        else:
            data[i]=1

    dataMin = min(data)
    dataMax = max(data)
    (rows, cols) = getScreenDimensions()
    bins = [0] * cols
    binSize = (dataMax - dataMin - 1) / cols + 1
    maxCount = 0
    for key in data:
        count = data[key]
        if count > maxCount:
            maxCount = count
        bins[key // binSize] += count
    
    heightScale = lines / maxCount

# print a graph



# old ccount stuff
    lastCount=0
    lastItem=None
    for line in sys.stdin.readlines():
        if (line == lastItem):
            lastCount += 1
        else:
            if (lastCount > 0):
                print "%d:%s" % (lastCount, lastItem),
            lastCount = 1
            lastItem = line
    if (lastCount > 0):
        print "%d:%s" % (lastCount, lastItem),
