#!/usr/bin/env python3

# Similar to python's range() on the arguments, and prints the results, one per line
#
# Definition of range() at http://docs.python.org/library/functions.html#range
# This version allows floating point values

from sys import argv
from math import floor

def slrange(a, b, step):
  if (step > 0):
    while a<b:
      yield a
      a += step
  else:
    while a>b:
      yield a
      a += step


def val(a):
  fp = float(a)
  try:
    i = int(a)
  except ValueError:
    return fp
  if (i==floor(fp)):
    return i
  return fp

if __name__=='__main__':
  if len(argv)==2:
    args = (0, val(argv[1]), 1)
  elif len(argv)==3:
    args = (val(argv[1]), val(argv[2]), 1)
  elif len(argv)>3:
    args = (val(argv[1]), val(argv[2]), val(argv[3]))
  if args:
    for r in slrange(*args):
      print(r)
  else:
    print("Invalid number of arguments: %d" % len(argv))
